### PR TITLE
Customize class name and Tailwind theme key

### PR DESCRIPTION
**Pull request by KACAH**
Hey!

Sometimes it is useful to change default `spinner` class to something different. This allows to resolve conflicts between styles or apply spinner to already existing designs. I implemented this functionality, new test and minor README fixes. In addition I added option for changing Tailwind theme key too.

### CODE REVIEW

**Review by joshmanders — CHANGES_REQUESTED** [review]
Looks good to me, only request I have is make it so that you don't have to pass any config, you can do the following and get all default stuff.

*tailwind.config.js:*
```js
{
  plugins: [
    require('tailwindcss-spinner'),
  ]
}
```

**Comment by KACAH** [comment]
> Looks good to me, only request I have is make it so that you don't have to pass any config, 

But you don't have to. It should work fine if you use my version of plugin the way you did before

https://github.com/aniftyco/tailwindcss-spinner/tree/caf7433a4ff382396670df9789c7957af4a6f8ce#usage

I use empty object as default spinner config here:
https://github.com/aniftyco/tailwindcss-spinner/pull/10/commits/b76fcc4c08b6d162291eaf6544ba402c4e135c16#diff-168726dbe96b3ce427e7fedce31bb0bcR19

and default class name and theme key here

https://github.com/aniftyco/tailwindcss-spinner/pull/10/commits/b76fcc4c08b6d162291eaf6544ba402c4e135c16#diff-168726dbe96b3ce427e7fedce31bb0bcR93

As I mentioned in README - configuration is optional:

https://github.com/aniftyco/tailwindcss-spinner/pull/10/commits/9c4a3a3d61d07e717c651b798748d40b5bcd70da#diff-0730bb7c2e8f9ea2438b52e419dd86c9R46

> you can do the following and get all default stuff.
> 
> _tailwind.config.js:_
> 
> ```js
> {
>   plugins: [
>     require('tailwindcss-spinner'),
>   ]
> }
> ```

I don't think it is possible to do this without breaking backwards compatibility. Spinner plugin module exports factory function now, not the plugin itself.

https://github.com/aniftyco/tailwindcss-spinner/blob/caf7433a4ff382396670df9789c7957af4a6f8ce/index.js#L19

Did you mean?

> _tailwind.config.js:_
> 
> ```js
> {
>   plugins: [
>     require('tailwindcss-spinner')(),
>   ]
> }
> ```

**Comment by joshmanders** [comment]
> I don't think it is possible to do this without breaking backwards compatibility. Spinner plugin module exports factory function now, not the plugin itself.

I think this is a feature of tailwind if you pass it like that, as long as our plugin has default config will work.

Have to do some testing to make sure.

**Comment by KACAH** [comment]
> > I don't think it is possible to do this without breaking backwards compatibility. Spinner plugin module exports factory function now, not the plugin itself.
> 
> I think this is a feature of tailwind if you pass it like that, as long as our plugin has default config will work.

The feature of tailwind is to take a function (as plugin) and call it while initializing. In case of `tailwindcss-spinner` it must be this function

https://github.com/aniftyco/tailwindcss-spinner/blob/caf7433a4ff382396670df9789c7957af4a6f8ce/index.js#L20

not the one exported from index.js on line 19. The one on L19 is NOT the plugin. It is the plugin factory. This is the reason why you have to call the result of require() now even without my changes (as current README says).

https://github.com/aniftyco/tailwindcss-spinner/tree/caf7433a4ff382396670df9789c7957af4a6f8ce#usage

I can't change this behaviour without breaking backwards compatibility of `tailwindcss-spinner`. And I don't think I should. In any case this is not the point of my specific Pull Request. If we need this to work like you described, we should start another one.

> 
> Have to do some testing to make sure.

https://github.com/aniftyco/tailwindcss-spinner/pull/10/commits/643088341bf25fda875e63efd90db910d7cb6038#diff-1dd241c4cd3fd1dd89c570cee98b79ddR29

It doesn't pass.

**Review by joshmanders — APPROVED** [review]
Thanks for doing that check.. I agree. We'll look into it for next major version. This all looks good to me. Thank you!

**Comment by joshmanders** [comment]
Sorry this didn't get merged in @KACAH!

**Comment by KACAH** [comment]
> Sorry this didn't get merged in @KACAH!

Np ) Btw, waaay after our conversation about clean `require` and configuration parameters I actually found the way to make it work as you wanted. 

> Looks good to me, only request I have is make it so that you don't have to pass any config, you can do the following and get all default stuff.
> 
> _tailwind.config.js:_
> 
> ```js
> {
>   plugins: [
>     require('tailwindcss-spinner'),
>   ]
> }
> ```

There is a new pull request.

**Pull request merged**
