### PR TITLE
Add support for Tailwind v1.x

### LINKED ISSUE #2: Allow passing and array of names and colors to create multiple spinners at once
Instead of requiring the plugin multiple times, I think it would be a good idea being able to pass an array of objects to create multiple spinners at once.

### PR DESCRIPTION
**Pull request by hacknug**
This PR adds support for Tailwind v1.x and tests (yay :tada:). It also allows users to generate multiple spinners at once and configure the spinner's rotation speed.

@joshmanders we should enable TravisCI in the repo so we start getting feedback if things break 👍 

Closes #2.

### CODE REVIEW

**Review by joshmanders — APPROVED** [review]

**Comment by joshmanders** [comment]
Awesome work @hacknug. Travis is enabled and building now.

**Comment by joshmanders** [comment]
Gave you write permissions on the npm package too.

**Comment by hacknug** [comment]
@joshmanders thanks!

**Comment by hacknug** [comment]
@joshmanders just published the new version! 🎉

**Pull request merged**
